# deploy/docker-compose.yml
version: '3.8'

services:
  backend:
    build: ../backend
    ports:
      - "5000:5000"

  ai-engine:
    build: ../ai-engine
    ports:
      - "6000:6000"

  frontend:
    build: ../frontend
    ports:
      - "4200:4200"
    stdin_open: true
    tty: true